import io

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
)

from app.models.schemas import OptimizeResponse

router = APIRouter()

BRAND_DARK = colors.HexColor("#0B1220")
BRAND_EMERALD = colors.HexColor("#10B981")
BRAND_BLUE = colors.HexColor("#1E3A8A")


@router.post("/report/pdf")
def generate_pdf_report(result: OptimizeResponse):
    """Builds a downloadable PDF summary of an optimization result."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=20 * mm, bottomMargin=20 * mm)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Title"], textColor=BRAND_DARK, fontSize=22, spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle", parent=styles["Normal"], textColor=colors.HexColor("#475569"), fontSize=11, spaceAfter=16,
    )
    section_style = ParagraphStyle(
        "Section", parent=styles["Heading2"], textColor=BRAND_BLUE, spaceBefore=16, spaceAfter=8,
    )
    body_style = styles["Normal"]

    elements = [
        Paragraph("Portfolio Risk & Return Report", title_style),
        Paragraph("Generated by the Portfolio Optimizer — Modern Portfolio Theory engine", subtitle_style),
    ]

    # KPI table
    kpi_data = [
        ["Expected Return", f"{result.expected_return:.2f}%"],
        ["Portfolio Risk (Volatility)", f"{result.risk:.2f}%"],
        ["Sharpe Ratio", f"{result.sharpe:.2f}"],
        ["Investment Amount", f"₹{result.amount:,.0f}"],
        ["Projected Value", f"₹{result.projected_value:,.0f}"],
        ["Projected Profit", f"₹{result.projected_profit:,.0f}"],
        ["Diversification Score", f"{result.diversification_score:.1f} / 100"],
        ["Portfolio Health Score", f"{result.health_score:.1f} / 100"],
    ]
    kpi_table = Table(kpi_data, colWidths=[80 * mm, 80 * mm])
    kpi_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F1F5F9")),
        ("TEXTCOLOR", (0, 0), (-1, -1), BRAND_DARK),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
    ]))
    elements += [Paragraph("Key Metrics", section_style), kpi_table]

    # Allocation table
    alloc_header = ["Symbol", "Name", "Weight %", "Invested (₹)", "Projected Value (₹)", "Profit (₹)"]
    alloc_rows = [alloc_header] + [
        [
            a.symbol, a.name, f"{a.weight:.2f}%",
            f"{a.invested_amount:,.0f}", f"{a.projected_value:,.0f}", f"{a.projected_profit:,.0f}",
        ]
        for a in result.allocation
    ]
    alloc_table = Table(alloc_rows, colWidths=[18 * mm, 40 * mm, 20 * mm, 30 * mm, 32 * mm, 26 * mm])
    alloc_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
    ]))
    elements += [Paragraph("Portfolio Allocation", section_style), alloc_table]

    # Insights
    elements.append(Paragraph("Insights", section_style))
    for insight in result.insights:
        elements.append(Paragraph(f"• {insight}", body_style))
        elements.append(Spacer(1, 4))

    if result.is_simulated_data:
        elements.append(Spacer(1, 10))
        elements.append(Paragraph(
            "Note: live market data was unavailable when this report was generated, "
            "so simulated price data was used for demonstration purposes.",
            ParagraphStyle("Note", parent=body_style, textColor=colors.HexColor("#B45309"), fontSize=9),
        ))

    doc.build(elements)
    buffer.seek(0)
    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=portfolio_report.pdf"},
    )
